# Generated by Django 4.2 on 2023-04-21 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_review_tag_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Mashina', 'verbose_name_plural': 'Mashinalar'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Telefon', 'verbose_name_plural': 'Telefonlar'},
        ),
    ]
